authentication/urls.py
from django.urls import path

from . import views
from .views import assignmod
from .views import SignUpView
from .views import UserCommentariesView
from .views import UsersView
from .views import UserUpdateGroupDetail
from .views import UserUpdateView
from .views import UserView
from .views import UserWarnsView
from .views import verify_user
from .views import WarnCreateView
from .views import UsersViewSet
from .views import UserViewSet

urlpatterns = [
    path("api/users", UsersViewSet.as_view({'get': 'list', 'post': 'create'}), name="users_api"),
    path("api/users/<int:pk>", UserViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name="user_api"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("logout/", views.custom_logout, name="logout"),
    path("login/", views.sign_in, name="login"),
    path("users/", UsersView.as_view(), name="users"),
    path("users/<int:pk>", UserView.as_view(), name="user"),
    path(
        "users/<int:pk>/commentaries",
        UserCommentariesView.as_view(),
        name="user_commentaries",
    ),
    path("users/<int:pk>/warns", UserWarnsView.as_view(), name="user_warns"),
    path("users/<int:pk>/update", UserUpdateView.as_view(), name="user_update"),
    path(
        "users/<int:pk>/update/groups",
        UserUpdateGroupDetail.as_view(),
        name="user_group",
    ),
    path("users/<int:user_id>/update/groups/verify", verify_user, name="verify_user"),
    path("users/<int:user_id>/update/groups/moderator", assignmod, name="assignmod"),
    path("users/<int:pk>/delete", views.user_delete, name="user_delete"),
    path("users/<int:user_id>/warns/create", WarnCreateView.as_view(), name="warn_create"),
    path("warns/<int:pk>/delete", views.warn_delete, name="warn_delete"),
    path("feeds/", views.redirectURL, name="redirect_feeds"),
]

feeds/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from .views import FeedCreateView
from .views import FeedsView
from .views import FeedUpdateView
from .views import FeedView
from .views import FeedsViewSet
from .views import FeedViewSet
from .views import FeedCreateAPIView


urlpatterns = [
    path("", login_required(FeedsView.as_view()), name="feeds"),
    path("api/feeds", FeedsViewSet.as_view({'get': 'list', 'post': 'create'}), name="feeds_api"),
    path("api/feeds/<int:pk>", FeedViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name="feeds_api_detail"),
    path("feeds/create", FeedCreateView.as_view(), name="feed_create"),
    path("feeds/<int:pk>", FeedView.as_view(), name="feed"),
    path("feeds/<int:pk>/update", FeedUpdateView.as_view(), name="feed_update"),
    path("feeds/<int:pk>/delete", views.feed_delete, name="feed_delete"),
]

project/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("feeds.urls")),
    path("", include("commentary.urls")),
]

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
class User(AbstractUser):
    first_name = models.CharField(max_length=100, verbose_name=_("Vorname"))
    last_name = models.CharField(max_length=100, verbose_name=_("Nachname"))
    username = models.EmailField(unique=True, verbose_name="Benutzername")
    email = models.EmailField(unique=True, verbose_name="E-Mail Adresse")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]
    birthdate = models.DateField(null=True, verbose_name=_("Geburtsdatum"))
    verified = models.BooleanField(null=True)

class Warn(models.Model):
    class Reasons(models.TextChoices):
        MISINFORMATION = _("Falschinformationen"), _("Falschinformationen")
        ABUSE = _("Missbrauch von Privilegien"), _("Missbrauch von Privilegien")
        HARASSMENT = _("Belästigung"), _("Belästigung")
        BULLYING = _("Cybermobing"), _("Cybermobbing")
        GROOMING = _("Cybergrooming"), _("Cybergrooming")
        WHATABOUTISM = _("Whataboutismus"), _("Whataboutismus")
        RELATIVISATION = _("Relativierung"), _("Relativierung")
        BLACKMAILING = _("Erpressung"), _("Erpressung")
        THREAT = _("Drohung"), _("Drohung")
        COW = _("Wortwahl"), _("Wortwahl")
        HATESPEECH = _("Hassrede"), _("Hassrede")
        SWEARWORD = _("Beleidigung"), _("Beleidigung")
        DISCRIMINATION = _("Diskriminierung"), _("Diskriminierung")
        SEXISM = _("Sexismus"), _("Sexismus")
        RACISM = _("Rassismus"), _("Rassismus")
        FACISM = _("Faschismus"), _("Faschismus")
        ANTISEMITISM = _("Antisemitismus"), _("Antisemitismus")
        SCAM = _("Betrug"), _("Betrug")
        SPAM = _("Spam"), _("Spam")

    reason = models.CharField(max_length=30, choices=Reasons.choices, default=Reasons.HATESPEECH, verbose_name=_("Grund"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="warns")

authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class SignUpForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "birthdate",
            "email",
            "password",
        ]
        labels = {
            "first_name": _("Vorname"),
            "last_name": _("Nachname"),
            "username": _("Benutzername"),
            "birthdate": _("Geburtsdatum"),
            "email": _("E-Mail Adresse"),
            "password": _("Passwort"),
        }
        help_texts = {"username": ""}
        error_messages = {"name": {"required": "Pflichtfeld"}}

    def save(self, commit=True):
        user = super().save(commit=commit)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(label=_("Benutzername"))
    password = forms.CharField(widget=forms.PasswordInput, label=_("Passwort"))

authentication/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from rest_framework import generics, status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from .permissions import CanViewUserPermission, CanAddUserPermission, CanChangeUserPermission, CanDeleteUserPermission
from .serializers import UserSerializer
from rest_framework.generics import ListAPIView, RetrieveAPIView, CreateAPIView, UpdateAPIView, DestroyAPIView
from rest_framework.authentication import SessionAuthentication

from authentication.models import Warn

from .forms import LoginForm
from .forms import SignUpForm

from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken

User = get_user_model()

def can_verify(user):
    return user.groups.filter(name__in=["moderator", "administrator"]).exists()


def can_assignmod(user):
    return user.groups.filter(name__in=["administrator"]).exists()


@login_required
@user_passes_test(can_verify, login_url="/feeds/")
def verify_user(request, user_id):
    user = get_object_or_404(User, id=user_id)

    if request.method == "POST":
        verified_group = Group.objects.get_or_create(name="verified")
        if user.groups.filter(name="verified").exists():
            user.groups.remove(verified_group)
        else:
            user.groups.add(verified_group)
        return redirect("user_group", user.id)
    else:
        return render(request, "authentication/user_group_verify.html", {"user": user})


@login_required
@user_passes_test(can_assignmod, login_url="/feeds/")
def assignmod(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == "POST":
        moderator_group = Group.objects.get(name="moderator")
        if user.groups.filter(name="moderator").exists():
            user.groups.remove(moderator_group)
        else:
            user.groups.add(moderator_group)
        return redirect("user_group", user.id)
    else:
        return render(request, "authentication/user_group_moderator.html", {"user": user})


def logout_view(request):
    logout(request)


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy("login")
    template_name = "authentication/signup.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        # group = Group.objects.get_or_create(name="default")
        # self.object.groups.add(group)
        return response


@login_required
def custom_logout(request):
    logout(request)
    return redirect("login")


def sign_in(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect("/")
        form = LoginForm()
        return render(request, "authentication/login.html", {"form": form})

    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, email=email, password=password)
            if user:
                login(request, user)
                messages.success(request, "Erfolgreich angemeldet!")
                return redirect("feeds")

        messages.error(request, "Benutzername oder Passwort ist falsch.")
        return render(request, "authentication/login.html", {"form": form})


class UsersView(generic.ListView):
    model = User
    fields = [
        "first_name",
        "last_name",
        "username",
        "email",
        "password",
        "birthdate",
        "verified",
    ]
    template_name = "authentication/users.html"

class UsersViewSet(ModelViewSet):
    authentication_classes = [SessionAuthentication]
    permission_classes = [CanViewUserPermission]
    queryset = User.objects.all()
    serializer_class = UserSerializer
    
    def get_permissions(self):
        if self.action == 'create':
            return [CanAddUserPermission()]

        return super().get_permissions()

class UserView(generic.DetailView):
    model = User
    template_name = "authentication/user.html"

class UserViewSet(ModelViewSet):
    authentication_classes = [SessionAuthentication]
    permission_classes = [CanViewUserPermission]
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_permissions(self):
        if self.action == 'create':
            return [CanAddUserPermission()]
        elif self.action == 'update':
            return [CanChangeUserPermission()]
        elif self.action == 'destroy':
            return [CanDeleteUserPermission()]

        return super().get_permissions()

class UserCommentariesView(generic.DetailView):
    model = User
    template_name = "authentication/user_commentaries.html"


class UserWarnsView(generic.DetailView):
    model = User
    template_name = "authentication/user_warns.html"


def redirectURL(request):
    return redirect("feeds")

class UserUpdateView(generic.UpdateView):
    model = User
    fields = ["first_name", "last_name", "username", "email", "birthdate"]
    template_name = "authentication/user_update.html"

    def get_success_url(self):
        return reverse_lazy("user", args=[self.object.pk])

    def form_valid(self, form):
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update"] = True
        return context

class UserAPIUpdateView(UpdateAPIView):
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = User.objects.all()
    serializer_class = UserSerializer

def user_delete(request, pk):
    user = User.objects.get(pk=pk)

    if request.method == "POST":
        user.delete()
        return redirect("feeds")
    return (request, "authentication/user_delete.html", {"user": user})


class WarnCreateView(generic.CreateView):
    model = Warn
    fields = ["reason"]
    template_name = "authentication/warn_create.html"

    def get_success_url(self):
        return reverse_lazy("user_warns", kwargs={"pk": self.kwargs.get("user_id")})

    def get_current_user(self, **kwargs):
        return User.objects.get(id=self.kwargs.get("user_id"))

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        user = self.get_current_user(**kwargs)
        data.update({"user": user})
        return data

    def form_valid(self, form):
        form.instance.user = self.get_current_user(**self.kwargs)
        return super().form_valid(form)


def warn_delete(request, pk):
    warn = get_object_or_404(Warn, pk=pk)

    if request.method == "POST":
        user_id = warn.user.id
        warn.delete()
        return redirect("user_warns", pk=user_id)
    return JsonResponse({"success": False})


class UserUpdateGroupDetail(generic.DetailView):
    model = User
    template_name = "authentication/user_group.html"

authentication/templates/authentication/user.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'users.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'feeds.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% translate "Profil" %}</title>
</head>
<body>
<header>
    <div class="grid-header">
        <h1 class="title">{% translate "Profil" %}</h1>
        <div class="profile">
            <a href="{% url 'user' request.user.id %}"><img src="{% static 'svgs/account.svg' %}" height="40px"/></a>
        </div>
    </div>
</header>
<main>
    {% if request.user.id == user.id or perms.authentication.view_user %}
        <div class="grid-buttons grid-buttons-user">
            <a href="{% url 'feeds' %}" class="crud-button back">
                <img src="{% static 'svgs/back.svg' %}" height="25px"/>
            </a>
            {% if request.user.id == user.id or perms.authentication.change_user %}
                <a href="{% url 'user_update' user.id %}" class="crud-button update">
                    <img src="{% static 'svgs/settings.svg' %}" height="25px"/>
                </a>
            {% endif %}
        </div>
        <div>
            <div class="user">
                <div class="fulname-container">
                    {% if user.first_name != "" and user.last_name %}
                        <p class="fulname">{{ user.first_name }} {{ user.last_name }}</p>
                    {% else %}
                        <p class="fulname">{% translate "Unbekannt" %}</p>
                    {% endif %}
                    {% if user %}
                        {% for group in user.groups.values %}
                            {% if group.name == "verified" %}
                                <img class="verify" src="{% static 'svgs/verified.svg' %}" height="15px"/>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
                <p class="email">{{ user.email }}</p>
            </div>
        </div>
        <div class="grid-tab feeds">
            <a class="tab">
                {% translate "Feeds" %}
            </a>
            <a href="{% url 'user_commentaries' user.id %}" class="tab replies">
                {% translate "Antworten" %}
            </a>
            <a href="{% url 'user_warns' user.id %}" class="tab warns">
                {% translate "Verstösse" %}
            </a>
            <div class="current">

            </div>
        </div>
        <div class="count">
            {% if user.feeds.count > 1 or user.feeds.count < 1 %}
                <p>{{ user.feeds.count }} {% translate "Feeds" %}</p>
            {% else %}
                <p>{{ user.feeds.count }} {% translate "Feed" %}</p>
            {% endif %}
        </div>
        <div class="grid-feeds">
        {% for feed in user.feeds.all %}
            {% if feed.author.id == user.id %}
                <a href={% url 'feed' feed.id %}>
                    <div class="card feed">
                        <div class="author">
                            <div class="fulname-container">
                                {% if feed.author.first_name != "" and feed.author.last_name != "" %}
                                    <p class="fulname">{{ feed.author.first_name }} {{ feed.author.last_name }}</p>
                                {% else %}
                                    <p class="fulname">{% translate "Unbekannt" %}</p>
                                {% endif %}
                                {% for group in feed.author.groups.values %}
                                    {% if group.name == "verified" %}
                                        <img class="verify" src="{% static 'svgs/verified.svg' %}" height="15px"/>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <p class="email">{{ feed.author.email }}</p>
                        </div>
                        <div class="text">
                            <p>{{ feed.text }}</p>
                        </div>
                    </div>
                </a>
            {% endif %}
        {% endfor %}
    {% else %}
        <div class="no-perm">
            <p>{% translate "Zugriff verweigert" %}</p>
        </div>
    {% endif %}
</main>
</body>

authentication/templates/authentication/user_commentaries.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'users.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'feeds.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
<header>
    <div class="grid-header">
        <h1 class="title">{% translate "Profil" %}</h1>
        <div class="profile">
            <a href="{% url 'user' request.user.id %}"><img src="{% static 'svgs/account.svg' %}" height="40px"/></a>
        </div>
    </div>
</header>
<main>
    {% if request.user.id == user.id or perms.authentication.view_user %}
        <div class="grid-buttons grid-buttons-user">
            <a href="{% url 'feeds' %}" class="crud-button back">
                <img src="{% static 'svgs/back.svg' %}" height="25px"/>
            </a>
            {% if request.user.id == user.id or perms.authentication.change_user %}
                <a href="{% url 'user_update' user.id %}" class="crud-button update">
                    <img src="{% static 'svgs/settings.svg' %}" height="25px"/>
                </a>
            {% endif %}
        </div>
        <div>
            <div class="user">
                <div class="fulname-container">
                    {% if user.first_name != "" and user.last_name %}
                        <p class="fulname">{{ user.first_name }} {{ user.last_name }}</p>
                    {% else %}
                        <p class="fulname">{% translate "Unbekannt" %}</p>
                    {% endif %}
                    {% if user %}
                        {% for group in user.groups.values %}
                            {% if group.name == "verified" %}
                                <img class="verify" src="{% static 'svgs/verified.svg' %}" height="15px"/>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
                <p class="email">{{ user.email }}</p>
            </div>
        </div>

        <div class="grid-tab-commentaries feeds">
            <a href="{% url 'user' user.id %}" class="tab">
                {% translate "Feeds" %}
            </a>
            <a class="tab replies">
                {% translate "Antworten" %}
            </a>
            <a href="{% url 'user_warns' user.id %}" class="tab warns">
                {% translate "Verstösse" %}
            </a>
            <div class="current">
            </div>
        </div>
        <div class="count">
            {% if user.commentaries.count > 1 or user.commentaries.count < 1 %}
                <p>{{ user.commentaries.count }} {% translate "Kommentare" %}</p>
            {% else %}
                <p>{{ user.commentaries.count }} {% translate "Kommentar" %}</p>
            {% endif %}
        </div>
        <div class="grid-commentaries">
            {% for commentary in user.commentaries.all %}
                <a href="{% url 'feed' commentary.feed.id %}">
                    <div class="card feed">
                        <div class="author">
                            <div class="fulname-container">
                                {% if commentary.feed.author.first_name != "" and commentary.feed.author.last_name != "" %}
                                    <p class="fulname">{{ commentary.feed.author.first_name }} {{ commentary.feed.author.last_name }}</p>
                                {% else %}
                                    <p class="fulname">{% translate "Unbekannt" %}</p>
                                {% endif %}
                                {% for group in commentary.feed.author.groups.values %}
                                    {% if group.name == "verified" %}
                                        <img class="verify" src="{% static 'svgs/verified.svg' %}" height="15px"/>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <p class="email">{{ commentary.feed.author.email }}</p>
                        </div>
                        <div class="text">
                            <p>{{ commentary.feed.text }}</p>
                        </div>
                    </div>
                    <div class="card commentary">
                        <div class="answer">
                            <p>Antwort an <span class="answer-email">{{ commentary.feed.author.email }}</span></p>
                        </div>
                        <div class="author">
                            <div class="fulname-container">
                                {% if commentary.author.first_name != "" and commentary.author.last_name != "" %}
                                    <p class="fulname">{{ commentary.author.first_name }} {{ commentary.author.last_name }}</p>
                                {% else %}
                                    <p class="fulname">{% translate "Unbekannt" %}</p>
                                {% endif %}
                                {% for group in commentary.author.groups.values %}
                                    {% if group.name == "verified" %}
                                        <img class="verify" src="{% static 'svgs/verified.svg' %}" height="15px"/>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <p class="email">{{ commentary.author.email }}</p>
                        </div>
                        <div class="text">
                            <p>{{ commentary.text }}</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
        <div class="no-perm">
            <p>{% translate "Zugriff verweigert" %}</p>
        </div>
    {% endif %}
</main>

authentication/templates/authentication/user_update.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'users.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'feeds.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
<header>
    <div class="grid-header">
        <h1 class="title">{% translate "Profil Bearbeiten" %}</h1>
        <div class="profile">
            <a href="{% url 'user' request.user.id %}"><img src="{% static 'svgs/account.svg' %}" height="40px"/></a>
        </div>
    </div>
</header>
<main>
    {% if request.user.id == user.id or perms.authentication.change_user %}
        <div class="grid-buttons grid-buttons-user-update">
            <a href="{% url 'user' user.id %}" class="crud-button back">
                <img src="{% static 'svgs/back.svg' %}" height="25px"/>
            </a>
            {% if request.user.id == user.id %}
                <a href="{% url 'logout' %}" class="crud-button logout">
                    <img src="{% static 'svgs/logout.svg' %}" height="25px"/>
                </a>
            {% endif %}
            {% if request.user.id == user.id or perms.authentication.delete_user %}
                <form class="delete" action="{% url 'user_delete' user.id %}" method="POST">
                    {% csrf_token %}
                    <input type="image" src="{% static 'svgs/delete.svg' %}" value=""/>
                </form>
            {% endif %}
            {% if perms.authentication.change_user %}
                <a href="{% url 'user_group' user.id %}" class="crud-button tree">
                    <img src="{% static 'svgs/tree.svg' %}" height="25px"/>
                </a>
            {% endif %}
        </div>
        <div class="card">
            <form class="form-container" method="POST">
                <div>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">{% translate "Speichern" %}</button>
                </div>
            </form>
        </div>
    {% else %}
        <div class="no-perm">
            <p>{% translate "Zugriff verweigert" %}</p>
        </div>
    {% endif %}
</main>

authentication/templates/authentication/user_warns.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'users.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'feeds.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% translate "Profil" %}</title>
</head>
<body>
<header>
    <div class="grid-header">
        <h1 class="title">{% translate "Profil" %}</h1>
        <div class="profile">
            <a href="{% url 'user' request.user.id %}"><img src="{% static 'svgs/account.svg' %}" height="40px"/></a>
        </div>
    </div>
</header>
<main>
    {% if request.user.id == user.id or perms.authentication.view_user %}
        <div class="grid-buttons grid-buttons-user">
            <a href="{% url 'feeds' %}" class="crud-button back">
                <img src="{% static 'svgs/back.svg' %}" height="25px"/>
            </a>
            {% if request.user.id == user.id or perms.authentication.change_user %}
                <a href="{% url 'user_update' user.id %}" class="crud-button update">
                    <img src="{% static 'svgs/settings.svg' %}" height="25px"/>
                </a>
            {% endif %}
        </div>
        <div class="user">
            <div class="fulname-container">
                {% if user.first_name != "" and user.last_name %}
                    <p class="fulname">{{ user.first_name }} {{ user.last_name }}</p>
                {% else %}
                    <p class="fulname">{% translate "Unbekannt" %}</p>
                {% endif %}
                {% if user %}
                    {% for group in user.groups.values %}
                        {% if group.name == "verified" %}
                            <img class="verify" src="{% static 'svgs/verified.svg' %}" height="15px"/>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
            <p class="email">{{ user.email }}</p>
        </div>
        <div class="grid-tab-warns feeds">
            <a href="{% url 'user' user.id %}" class="tab">
                {% translate "Feeds" %}
            </a>
            <a href="{% url 'user_commentaries' user.id %}" class="tab replies">
                {% translate "Antworten" %}
            </a>
            <a class="tab warns">
                {% translate "Verstösse" %}
            </a>
            <div class="current">
            </div>
        </div>
        {% if request.user.id == user.id or perms.authentication.view_warn %}
            <div class="count">
                {% if user.warns.count > 1 or user.warns.count < 1 %}
                    <p>{{ user.warns.count }} {% translate "Verwarnungen" %}</p>
                {% else %}
                    <p>{{ user.warns.count }} {% translate "Verwarnung" %}</p>
                {% endif %}
            </div>
            {% if perms.authentication.add_warn and request.user.id != user.id %}
                <div class="grid-buttons grid-buttons-home">
                    <a href="{% url 'warn_create' user.id %}" class="crud-button create">
                        <img src="{% static 'svgs/add.svg' %}" height="25px"/>
                    </a>
                </div>
            {% endif %}
            <div class="grid-warns">
                {% for warn in user.warns.all %}
                    <div class="card warn">
                        <div class="text">
                            <p>{{ warn.reason }}</p>
                        </div>
                        {% if perms.authentication.delete_warn %}
                            <form action="{% url 'warn_delete' warn.id %}" class="delete-container" method="post">
                                {% csrf_token %}
                                <input type="submit" class="delete" value="x"/>
                            </form>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="no-perm">
                <p>{% translate "Zugriff verweigert" %}</p>
            </div>
        {% endif %}
    {% else %}
        <div class="no-perm">
            <p>{% translate "Zugriff verweigert" %}</p>
        </div>
    {% endif %}
</main>