commentary/urls.py
from django.urls import path

from . import views
from .views import CommentaryCreateView
from .views import CommentaryUpdateView
from .views import CommentaryView
from .views import CommentariesAPIView
from .views import CommentaryViewSet
from .views import CommentaryCreateAPIView

urlpatterns = [
    path("api/commentaries/", CommentariesAPIView.as_view(), name="commentaries_api"),
    path('api/commentaries/<int:pk>/', CommentaryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name="commentary_api"),
    path("api/feeds/<int:feed_id>/commentaries/create", CommentaryCreateAPIView.as_view(), name="commentary_api_create"),
    path(
        "feeds/<int:feed_id>/commentaries/create",
        CommentaryCreateView.as_view(),
        name="commentary_create",
    ),
    path("commentaries/<int:pk>", CommentaryView.as_view(), name="commentary"),
    path(
        "commentaries/<int:pk>/update",
        CommentaryUpdateView.as_view(),
        name="commentary_update",
    ),
    path(
        "commentaries/<int:pk>/delete",
        views.commentary_delete,
        name="commentary_delete",
    ),
]

feeds/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from .views import FeedCreateView
from .views import FeedsView
from .views import FeedUpdateView
from .views import FeedView
from .views import FeedsViewSet
from .views import FeedViewSet
from .views import FeedCreateAPIView


urlpatterns = [
    path("", login_required(FeedsView.as_view()), name="feeds"),
    path("api/feeds", FeedsViewSet.as_view({'get': 'list', 'post': 'create'}), name="feeds_api"),
    path("api/feeds/<int:pk>", FeedViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name="feeds_api_detail"),
    path("feeds/create", FeedCreateView.as_view(), name="feed_create"),
    path("feeds/<int:pk>", FeedView.as_view(), name="feed"),
    path("feeds/<int:pk>/update", FeedUpdateView.as_view(), name="feed_update"),
    path("feeds/<int:pk>/delete", views.feed_delete, name="feed_delete"),
]

project/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("feeds.urls")),
    path("", include("commentary.urls")),
]

commentary/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext, gettext_lazy as _
from django.utils import timezone
from datetime import datetime, time
from authentication.blacklist import censorer
from authentication.blacklist import is_blacklisted
from authentication.models import Warn
from feeds.models import Feed


User = get_user_model()


class Commentary(models.Model):
    text = models.TextField(max_length=200, verbose_name=_("Inhalt"))
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE, related_name="commentaries")
    published_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Veröffentlicht"))
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentaries")

    def time_since_published(self):
        now = timezone.now()
        diff = now - self.published_date

        if diff.days >= 365:
            count = diff.days // 365
            return _("Vor {count} Jahr{plural}").format(count=count, plural=_('e') if count > 1 else '')
        elif diff.days >= 30:
            count = diff.days // 30
            return _("Vor {count} Monat{plural}").format(count=count, plural=_('e') if count > 1 else '')
        elif diff.days > 0:
            return _("Vor {count} Tag{plural}").format(count=diff.days, plural=_('e') if diff.days > 1 else '')
        elif diff.seconds >= 3600:
            count = diff.seconds // 3600
            return _("Vor {count} Stunde{plural}").format(count=count, plural=_('n') if count > 1 else '')
        elif diff.seconds >= 60:
            count = diff.seconds // 60
            return _("Vor {count} Minute{plural}").format(count=count, plural=_('n') if count > 1 else '')
        else:
            return _("Gerade eben")

    def save(self, *args, **kwargs):
        if is_blacklisted(self.text):
            self.text = censorer(self.text)
            Warn.objects.create(user=self.author, reason="Wortwahl")
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["-published_date", "-id"]

commentary/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet

from commentary.models import Commentary
from feeds.models import Feed
from rest_framework import generics
from rest_framework.response import Response

from .permissions import CanAddCommentaryPermission, CanChangeCommentaryPermission, CanDeleteCommentaryPermission, \
    CanViewCommentaryPermission
from .serializers import CommentarySerializer
from rest_framework.generics import ListAPIView, RetrieveAPIView, CreateAPIView, UpdateAPIView, DestroyAPIView


class CommentariesAPIView(ListAPIView):
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = Commentary.objects.all()
    serializer_class = CommentarySerializer

class CommentaryView(generic.DetailView):
    model = Commentary
    template_name = "commentary/commentary.html"


class CommentaryViewSet(ModelViewSet):
    authentication_classes = [SessionAuthentication]
    permission_classes = [CanViewCommentaryPermission]
    queryset = Commentary.objects.all()
    serializer_class = CommentarySerializer

    def get_permissions(self):
        if self.action == 'create':
            return [CanAddCommentaryPermission()]
        elif self.action == 'update':
            return [CanChangeCommentaryPermission()]
        elif self.action == 'destroy':
            return [CanDeleteCommentaryPermission()]

        return super().get_permissions()

class CommentaryCreateView(generic.CreateView):
    model = Commentary
    fields = ["text"]
    template_name = "commentary/create.html"

    def get_success_url(self):
        return reverse_lazy("feed", kwargs={"pk": self.kwargs.get("feed_id")})

    def get_current_feed(self, **kwargs):
        return Feed.objects.get(id=self.kwargs.get("feed_id"))

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        feed = self.get_current_feed(**kwargs)
        data.update({"feed": feed})
        return data

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.feed = self.get_current_feed(**self.kwargs)
        return super().form_valid(form)


class CommentaryCreateAPIView(CreateAPIView):
    authentication_classes = [SessionAuthentication]
    permission_classes = [CanAddCommentaryPermission]
    serializer_class = CommentarySerializer

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['feed_id'] = self.kwargs['feed_id']  # Update this line
        return context

    def perform_create(self, serializer):
        serializer.save(author=self.request.user, feed_id=self.kwargs['feed_id'])

class CommentaryUpdateView(generic.UpdateView):
    model = Commentary
    fields = ["text"]
    template_name = "commentary/update.html"

    def get_success_url(self):
        return reverse_lazy("commentary", kwargs={"pk": self.kwargs["pk"]})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

def commentary_delete(request, pk):
    commentary = Commentary.objects.get(pk=pk)

    if request.method == "POST":
        feed_id = commentary.feed.id
        commentary.delete()
        return redirect("feed", pk=feed_id)

    return (request, "commentary/delete.html", {"commentary": commentary})

commentary/templates/commentary/commentary.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'feeds.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% translate "Detailansicht" %}</title>
</head>
<body>
<header>
    <div class="grid-header">
        <h1 class="title">{% translate "Detailansicht" %}</h1>
        <div class="profile">
            <a href="{% url 'user' request.user.id %}"><img src="{% static 'svgs/account.svg' %}" height="40px"/></a>
        </div>
    </div>
</header>
<main>
    {% if request.user.id == commentary.author.id or perms.commentary.view_commentary %}
        <div class="grid-buttons grid-buttons-detail">
            <a href="{% url 'feed' commentary.feed.id %}" class="crud-button back">
                <img src="{% static 'svgs/back.svg' %}" height="25px"/>
            </a>
            {% if request.user.id == commentary.author.id or perms.commentary.change_commentary %}
                <a href="{% url 'commentary_update' commentary.id %}" class="crud-button update">
                    <img src="{% static 'svgs/edit.svg' %}" height="25px"/>
                </a>
            {% endif %}
            {% if request.user.id == commentary.author.id or perms.commentary.delete_commentary or commentary.feed.author.id == user.id %}
                <form class="delete" action="{% url 'commentary_delete' commentary.id %}" method="post">
                    {% csrf_token %}
                    <input type="image" src="{% static 'svgs/delete.svg' %}" value=""/>
                </form>
            {% endif %}
        </div>
        <div class="card commentary">
            <div class="answer">
                <p>Antwort an <a href="{% url 'feed' commentary.feed.id %}"
                                 class="answer-email">{{ commentary.feed.author.email }}</a></p>
            </div>
            <a href="{% url 'user' commentary.author.id %}" class="author">
                <div class="fulname-container">
                    {% if commentary.author.first_name != "" and commentary.author.last_name != "" %}
                        <p class="fulname">{{ commentary.author.first_name }} {{ commentary.author.last_name }}</p>
                    {% else %}
                        <p class="fulname">Unknown</p>
                    {% endif %}
                    {% if user %}
                        {% for group in commentary.author.groups.values %}
                            {% if group.name == "verified" %}
                                <img class="verify" src="{% static 'svgs/verified.svg' %}" height="15px"/>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
                <p class="email">{{ commentary.author.email }}</p>
            </a>
            <div class="text">
                <p>{{ commentary.text }}</p>
            </div>
            <div class="published">
                <p>{{ commentary.time_since_published }}</p>
            </div>
        </div>
    {% else %}
        <div class="no-perm">
            <p>Zugriff verweigert</p>
        </div>
    {% endif %}
</main>
</body>

commentary/templates/commentary/create.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'feeds.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% translate "Kommentar Erstellen" %}</title>
</head>
<body>
<header>
    <div class="grid-header">
        <h1 class="title">{% translate "Kommentar Erstellen" %}</h1>
        <div class="profile">
            <a href="{% url 'user' request.user.id %}"><img src="{% static 'svgs/account.svg' %}" height="40px"/></a>
        </div>
    </div>
</header>
<main>
    {% if perms.commentary.add_commentary %}
        <div class="grid-buttons grid-buttons-detail">
            <a href="{% url 'feed' feed.id %}" class="crud-button back">
                <img src="{% static 'svgs/back.svg' %}" height="25px"/>
            </a>
        </div>
        <div class="card feed">
            <a href="{% url 'user' feed.author.id %}" class="author">
                <div class="fulname-container">
                    {% if feed.author.first_name != "" and feed.author.last_name != "" %}
                        <p class="fulname">{{ feed.author.first_name }} {{ feed.author.last_name }}</p>
                    {% else %}
                        <p class="fulname">{% translate "Unbekannt" %}</p>
                    {% endif %}
                    {% for group in feed.author.groups.values %}
                        {% if group.name == "verified" %}
                            <img class="verify" src="{% static 'svgs/verified.svg' %}" height="15px"/>
                        {% endif %}
                    {% endfor %}
                </div>
                <p class="email">{{ feed.author.email }}</p>
            </a>
            <div class="text">
                <p>{{ feed.text }}</p>
            </div>
        </div>
        <div class="card">
            <form class="form-container" method="POST">
                <div class="answer">
                    <p>Antwort an <a href="{% url 'feed' feed.id %}" class="answer-email">{{ feed.author.email }}</a>
                    </p>
                </div>
                {% if request.user.warns.count < 3 %}
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">{% translate "Posten" %}</button>
                {% else %}
                    <div class="no-perm">
                        <p>{% translate "Dein Konto wurde gesperrt!" %}</p>
                    </div>
                {% endif %}
            </form>
        </div>
    {% else %}
        <div class="no-perm">
            <p>{% translate "Zugriff verweigert" %}</p>
        </div>
    {% endif %}
</main>

commentary/templates/commentary/update.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'feeds.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% translate "Kommentar Bearbeiten" %}</title>
</head>
<body>
<header>
    <div class="grid-header">
        <h1 class="title">{% translate "Kommentar Bearbeiten" %}</h1>
        <div class="profile">
            <a href="{% url 'user' request.user.id %}"><img src="{% static 'svgs/account.svg' %}" height="40px"/></a>
        </div>
    </div>
</header>
<main>
    {% if request.user.id == commentary.author.id or perms.commentary.change_commentary %}
        <div class="grid-buttons grid-buttons-detail">
            <a href="{% url 'feed' commentary.feed.id %}" class="crud-button back">
                <img src="{% static 'svgs/back.svg' %}" height="25px"/>
            </a>
        </div>
        <div class="card">
            <form class="form-container" method="POST">
                <div class="answer">
                    <p>Antwort an <a href="{% url 'feed' commentary.feed.id %}"
                                     class="answer-email">{{ commentary.feed.author.email }}</a></p>
                </div>
                {% if request.user.warns.count < 3 %}
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">{% translate "Speichern" %}</button>
                {% else %}
                    <div class="no-perm">
                        <p>{% translate "Dein Konto wurde gesperrt!" %}</p>
                    </div>
                {% endif %}
            </form>
        </div>
    {% else %}
        <div class="no-perm">
            <p>Zugriff verweigert</p>
        </div>
    {% endif %}
</main>